name: Update release branch
on:
  push:
    branches:
      - main
jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout theme source
        uses: actions/checkout@v2

      - name: Compile stylesheet
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: css/global.scss
          destination: css/build/global.css

      - name: Create swap directory
        run: |
          mkdir -vp /tmp/dvorak

      - name: Copy compiled theme to swap directory
        run: |
          cp -R * . /tmp/dvorak

      - name: DEBUG check swap directory
        run: |
          ls -l /tmp/dvorak

      - name: DEBUG 1 compare release and swap locations
        run: |
          diff . /tmp/dvorak

      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
            ref: release
            fetch-depth: 1

      - name: Copy compiled theme from swap directory
        run: |
          rsync -rlDz --delete --exclude '.git' /tmp/dvorak/ .

      - name: Add and commit changes to release branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .
          git add -f css/build/*
          git commit -m 'Updates theme including compiled assets'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

  create_release:
    needs: update_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This release created automatically. Changes made include:
            - First Change
            - Second Change
          draft: false
          prerelease: false
