name: Update release branch
on:
  push:
    branches:
      - master
jobs:
  build_css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/dvorak/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: css/global.scss
          destination: /tmp/dvorak/assets/css/global.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: release-prep
            fetch-depth: 1

      - name: Move compiled CSS to path within release branch
        run: mv /tmp/dvorak/assets/css/global.css css/build/global.css

      - name: Add and Commit changes to release branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f css/build/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-prep

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.4
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: release-prep
          base: release
          title: 'Updates site files from latest Actions build'
          body: >
            Perhaps a multi-line description
            about latest features and such.